version: "3.9"
services:
  app:
    build: ./infra/docker/app
    container_name: slim4_app
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "19000:9000"
    environment:
      - MYSQL_HOSTNAME=${DB_HOSTNAME:-db}
      - MYSQL_PORT=${DB_PORT:-3306}
      - MYSQL_DATABASE=${DB_NAME:-sample_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
  web:
    image: nginx:1.21.6-alpine
    container_name: slim4_web
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./public:/var/www/html/public
      - ./infra/docker/web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mariadb:10.3.34
    container_name: slim4_mariadb
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME:-sample_db}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-root}
